DROP TABLE WEBUSER.TB_INSTRUCTOR;
DROP TABLE WEBUSER.TB_PLAN;
DROP TABLE WEBUSER.TB_SCHEDULE;
DROP TABLE WEBUSER.TB_ACTIVITY;
DROP TABLE WEBUSER.TB_MEMBER;


CREATE TABLE WEBUSER.TB_INSTRUCTOR (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    address TEXT,
    phone VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_PLAN (
    id SERIAL PRIMARY KEY,
    plan VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_MEMBER (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    address TEXT,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    plan_type INTEGER REFERENCES WEBUSER.TB_PLAN(id),
    begin_date DATE NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_ACTIVITY (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    instructor INTEGER REFERENCES WEBUSER.TB_INSTRUCTOR(id) ON DELETE CASCADE,
    date TIMESTAMP NOT NULL,
    duration INT NOT NULL,
    capacity INT NOT NULL,
    plan_type INT REFERENCES WEBUSER.TB_PLAN(id),
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_SCHEDULE (
    id SERIAL PRIMARY KEY,
    activity INTEGER REFERENCES WEBUSER.TB_ACTIVITY(id) ON DELETE CASCADE,
    member INTEGER REFERENCES WEBUSER.TB_MEMBER(id) ON DELETE CASCADE
);